// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // URL para la CLI de Prisma (migrate/studio). En runtime, el cliente usa un
  // driver adapter (ver src/lib/db.ts), como exige Prisma 7.
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
